languageCode = "en"
languageName = "English"
weight = 1
title = "Bare Chart"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/blowfish_logo_transparent.png"
  description = "A no nonsense look at technical analysis of the markets"

[params.author]
  name = "Dan"
  email = "daniel@letterdrop.net"
  image = "img/blowfish_logo.png"
  headline = "A no nonsense look at technical anaysis of the markets"
  bio = "London Open trader"
  links = [
    { x-twitter = "https://twitter.com/burufugu" },
    { github = "https://github.com/nunocoracao/blowfish" },
  ]
