# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

# **** SEE config/_default/menus.en.toml ****

[[main]]
  name = "About"
  pageRef = "samples"
  weight = 10

[[main]]
  name = "Articles"
  pageRef = "samples"
  weight = 10

[[main]]
  name = "Blog"
  parent = "Articles"
  pageRef = "/posts/"
  weight = 20 

[[main]]
  name = "Personal Log"
  parent = "Articles"
  pageRef = "/personal-log/"
  weight = 20      

[[main]]
  name = "Teamwork Log"
  parent = "Articles"
  pageRef = "/teamwork/"
  weight = 20     

[[main]]
  name = "Mindset"
  pageRef = "samples"
  weight = 10

[[main]]
  name = "Education"
  pageRef = "samples"
  weight = 10

 [[main]]
  name = "Tools"
  pageRef = "samples"
  weight = 10 



