backend:
  name: github
  repo: aquada/barechart
  branch: main
  auth_type: implicit
  app_id: Ov23liWt0EGoUQFnNFU3

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "trades"
    label: "Trades"
    folder: "content/trades"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Trader", name: "trader", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Time", name: "time", widget: "string" }
      - { label: "Instrument", name: "instrument", widget: "string" }
      - { label: "Setup", name: "setup", widget: "text" }
      - { label: "Confluence Entry/SL", name: "confluence", widget: "text" }
      - { label: "Target", name: "target", widget: "text" }
      - { label: "Rules Followed", name: "rules", widget: "text" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Image", name: "image", widget: "image" }
